FROM golang:1.22-alpine AS builder

WORKDIR /src

COPY go.mod ./
COPY internal ./internal
COPY services ./services

ARG SERVICE
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/service ./services/${SERVICE}

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /out/service /app/service

EXPOSE 8080

ENTRYPOINT ["/app/service"]
